server:
  port: 1034

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: qaisar786
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    topic:
      order-status: order-status

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
