server:
  port: 1033

spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce_db
      database: ecommerce_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
